Sprint 3
Winterstein9/middle.messenger.praktikum.yandex pull request #6
Opened 2022-12-25 22:47 UTC by Winterstein9

2022-12-27 07:43 UTC, maks88sgt requested changes
Привет. У тебя получается интересный дизайн, но пока работа требует серьезной доработки. Основной момент связан с разбивкой приложения на модули. Текущее решение состоит из больших сложных модулей, которые решают сразу много различных задач. Например CChat.ts отвечает и за визуальную составляющую и за работу с АПИ и за реализацию бизнес-логики. Такой код очень тяжело читать и поддерживать. Предлагаю разделить эту функциональность между различными модулями. При реализации модулей нужно помнить о классах и наследовании ведь одна из целей данного раздела курса повторить ООП.
Второй момент - общий стиль кода. Необходимо до конца настроить eslint и на основе его правил переформатировать код и поправить ошибки которые он обнаружит. Сейчас код довольно трудно читается, т.к. не используются стандартные правила форматирования.

2022-12-27 07:43 UTC, maks88sgt commented on .eslintignore
> +/node_modules
Здесь гит ругается на отсутствие EOF. Вот здесь можно почитать почему это важно https://moviecultists.com/when-to-use-eof. В идеале было бы настроить ИДЕ чтобы это проставлялось автоматически.

2022-12-27 07:43 UTC, maks88sgt commented on components/cButton/cButton.ts
> +export default class ccButton extends Block{
Обычно стоит придерживаться подхода когда имя файла совпадает с именем класса внутри. Кроме того добавление каких-либо префиксов похоже на устаревшую венгерскую нотацию, когда с помощью них пытались передавать доп информацию о какой либо сущности. Думаю оптимально было бы вообще опустить этот префикс или дать более осмысленное имя

2022-12-27 07:43 UTC, maks88sgt commented on components/messages/messages.ts
> +export default new Messages(users).getMessages()*/
Закомментированный код лучше сразу удалять. Он не несет ничего полезного, только захламляет проект

2022-12-27 07:43 UTC, maks88sgt commented on components/mold/block.ts
> +     */
Использование JSDoc при наличии TS не имеет смысла. Плюс в проекте стоит придерживаться одинакового подхода везде, соответственно JSDoc должен быть либо везде, либо не использоваться совсем

2022-12-27 07:43 UTC, maks88sgt commented on .gitignore
> +.DS_Store
Здесь должны быть добавлены папки node_modules, dist и т.д.

2022-12-27 07:43 UTC, maks88sgt commented on package.json
> +    "chai": "^4.3.7",
В рекомендациях ко второму спринту предлагалось использовать фиксированные версии зависимостей. Давай будем придерживаться такого подхода.

2022-12-27 07:43 UTC, maks88sgt commented on package.json
> +    "start": "node express.js"
Здесь стоит добавить скрипт, который будет собирать билд а затем запускать сервер. Это пригодится для автоматического развертывания приложения.

2022-12-27 07:43 UTC, maks88sgt commented on controllers/chatList/ССhat.ts
> +}
Эти контроллеры следует разделить на отдельные модули - один, отвечающий за визуальные компоненты, второй - за отправку и обработку запросов. В текущей версии очень сложно разобраться как должен работать этот компонент.

2022-12-27 07:43 UTC, maks88sgt commented on controllers/chatList/ССhat.ts
> +        this.HTTPTransport.post("/chats",{method:"GET"}).then((chats)=>{
Во всех случаях отправки запросов следует добавить обработку ошибок на случай если что-то пойдет не так.

2022-12-27 07:43 UTC, maks88sgt commented on controllers/chatList/ССhat.ts
> +            let parent = document.querySelector(this.parentSelector)
В текущей имплементации объект parent остается неизменным (т.е. ссылка на область памяти где он хранится), меняется только его содержимое (данные по ссылке). В таких случаях принято использовать const.

2022-12-30 04:47 UTC, maks88sgt requested changes
Привет. Работа становиться лучше, но все равно осталось несколько довольно критичных моментов. Давай поправим их чтобы идти дальше:
1. Для всех случаев выполнения асинхронных запросов к серверу следует предусмотреть обработку возможных ошибок через try/catch
2. Во всех случаях, когда значение переменной не меняется в процессе выполнения кода принято использовать const вместо let. Это дает дополнительную защиту от возможных ошибок.
3. При именовании переменных/файлов и т.д. лучше избегать дополнительного уровня абстракции. Например у тебя в коде встречается переменная CL. Не понятно что это значит и что должно храниться здесь, т.к. здесь есть доп абстракция, очевидная только создателю кода. Или есть файл idea.ts - название pagesList или routes было бы более очевидным.
4. Не проходят автоматически тесты на гитхабе (проблема в первую очередь связана с тем что ты использовал yarn и есть проблемы с запуском скриптов через npm - проблема с некоторыми зависимостями, которые по разному подтягиваются yarn'ом и npm'ом).
Функциональность чата:
1. Если пользователь авторизован в системе то при попытке входа следует его сразу редиректить на страницу с чатами
2. Фактически роутинг не работает. При попытке перейти на страницы отличные от `/` приложение падает с ошибкой.
3. Ну и остальное я не смог проверить из-за недоступности этих страниц.

2022-12-30 04:47 UTC, maks88sgt commented on .eslintrc.json
> +  }
Здесь гит ругается на отсутствие EOF. Вот здесь можно почитать почему это важно https://moviecultists.com/when-to-use-eof. В идеале было бы настроить ИДЕ чтобы это делалось автоматически

2022-12-30 04:47 UTC, maks88sgt commented on controllers/change_img/CChange_img.ts
> +  yandexPathAvatar: string = "https://ya-praktikum.tech/api/v2/resources";
Лучше вынести это в отдельную переменную, потому что внутри класса это теряется. В идеале - в переменные окружения

2022-12-30 04:47 UTC, maks88sgt commented on controllers/change_img/CChange_img.ts
> +      let formData = new FormData();
Ссылка на объект не меняется, поэтому лучше здесь использовать const.

2022-12-30 04:47 UTC, maks88sgt commented on controllers/change_img/CChange_img.ts
> +    const userAvatar: string | null = localStorage.getItem("userAvatar");
Не совсем понятно зачем нам нужно хранение этих данных в localStorage.
Работу с localStorage лучше осуществлять через try/catch, т.к. при чтении или записи данных могут произойти ошибки

2022-12-30 04:47 UTC, maks88sgt commented on controllers/change_img/CChange_img.ts
> +          let avatarPath = this.yandexPathAvatar + ans.avatar;
Значение переменной здесь также не меняется. Следует использовать const

2022-12-30 04:47 UTC, maks88sgt commented on controllers/chat/CChat.ts
> +      let usersHTML: string = this.searchUser.makeUser(users);
Для всех случаев выполнения асинхронных запросов к серверу следует предусмотреть обработку возможных ошибок через try/catch

2022-12-30 04:47 UTC, maks88sgt commented on controllers/chat/CChat.ts
> +            if (this.activeChat != null) {
Такие условия обычно принято сокращать до 
```suggestion
            if (!this.activeChat) {
```

2022-12-30 04:47 UTC, maks88sgt commented on controllers/chat/CChat.ts
> +    do {
Обычно в книгах по программированию рекомендуют избегать циклов while и do/while, но в целом это допустимо

2022-12-30 04:47 UTC, maks88sgt commented on engine/HTTPTransport.ts
> +const commonPath = "https://ya-praktikum.tech/api/v2/";
Чтобы такие константы выделялись из основного кода принято использовать буквы в верхнем регистре https://learn.javascript.ru/variables#konstanty-v-verhnem-registre

2022-12-30 04:47 UTC, maks88sgt commented on engine/navigator.ts
> +      //this.setNavLinks(page);
Закомментированный код лучше сразу удалять из проекта

2022-12-30 04:47 UTC, maks88sgt commented on express.js
> +app.use(express.static(`${__dirname}/dist/`));
Сейчас сервер не умеет обрабатывать запросы, которые пойдут к нему по маршрутам отличным от `/`. Следует добавить доп хендлер для этого

2022-12-30 11:03 UTC, Winterstein9 commented on express.js
> +app.use(express.static(`${__dirname}/dist/`));
Привет. Все работает локально и по ссылке! Ошибка тестирования происходит при сборке проекта тестами как с npm так c yarn это ошибка тестов.

2022-12-30 11:10 UTC, Winterstein9 commented on express.js
> +app.use(express.static(`${__dirname}/dist/`));
> Сейчас сервер не умеет обрабатывать запросы, которые пойдут к нему по маршрутам отличным от `/`. Следует добавить доп хендлер для этого

Привет. Все работает локально и по ссылке! Ошибка тестирования происходит при сборке проекта тестами как с npm так c yarn это ошибка тестов. Без сборки проекта тесты проходят. Все основные задачи проекта выполнены. Прими проект, я целую неделю потеряю и не пройду 4 спринт!

2022-12-30 13:12 UTC, Winterstein9 commented on engine/navigator.ts
> +      //this.setNavLinks(page);
> Закомментированный код лучше сразу удалять из проекта

Этот код мне нужен для быстрого тестирования страниц

2022-12-30 13:13 UTC, Winterstein9 commented on controllers/chat/CChat.ts
> +    do {
> Обычно в книгах по программированию рекомендуют избегать циклов while и do/while, но в целом это допустимо

почему? никогда таких книг не читал. можешь порекомендовать?)

2022-12-30 13:18 UTC, Winterstein9 commented on controllers/change_img/CChange_img.ts
> +    const userAvatar: string | null = localStorage.getItem("userAvatar");
> Не совсем понятно зачем нам нужно хранение этих данных в localStorage. Работу с localStorage лучше осуществлять через try/catch, т.к. при чтении или записи данных могут произойти ошибки

Имя фото должно где-то храниться для доступа к нему, иначе доступ происходит через базу данных. Видимо это чтобы снизить нагрузку на БД и скорости загрузки фото. его нужно устанавливать здесь и при заходе в чат. Тогда будет только одно обращение к БД по поводу картинки.

2022-12-30 13:27 UTC, Winterstein9 commented on controllers/change_img/CChange_img.ts
> +  yandexPathAvatar: string = "https://ya-praktikum.tech/api/v2/resources";
> Лучше вынести это в отдельную переменную, потому что внутри класса это теряется. В идеале - в переменные окружения

но она нужна только в классе

2022-12-30 13:34 UTC, Winterstein9 commented
> Привет. Работа становиться лучше, но все равно осталось несколько довольно критичных моментов. Давай поправим их чтобы идти дальше:
> 
>     1. Для всех случаев выполнения асинхронных запросов к серверу следует предусмотреть обработку возможных ошибок через try/catch
> 
>     2. Во всех случаях, когда значение переменной не меняется в процессе выполнения кода принято использовать const вместо let. Это дает дополнительную защиту от возможных ошибок.
> 
>     3. При именовании переменных/файлов и т.д. лучше избегать дополнительного уровня абстракции. Например у тебя в коде встречается переменная CL. Не понятно что это значит и что должно храниться здесь, т.к. здесь есть доп абстракция, очевидная только создателю кода. Или есть файл idea.ts - название pagesList или routes было бы более очевидным.
> 
>     4. Не проходят автоматически тесты на гитхабе (проблема в первую очередь связана с тем что ты использовал yarn и есть проблемы с запуском скриптов через npm - проблема с некоторыми зависимостями, которые по разному подтягиваются yarn'ом и npm'ом).
> 
> 
> Функциональность чата:
> 
>     1. Если пользователь авторизован в системе то при попытке входа следует его сразу редиректить на страницу с чатами
> 
>     2. Фактически роутинг не работает. При попытке перейти на страницы отличные от `/` приложение падает с ошибкой.
> 
>     3. Ну и остальное я не смог проверить из-за недоступности этих страниц.

Никто не говорил что вы используете для этого исключительно экспресс, есть ссылка https://idyllic-sherbet-2a6ef8.netlify.app/ и yarn dev. Я менял yarn на npm но ничего не изменилось. Файл экспресс изменил, локально через экспресс у меня все работает. Но поскольку на гит загружается с ошибками при сборке, немного его изменил. Может это ошибка тестов?

2022-12-30 14:05 UTC, maks88sgt commented on controllers/chat/CChat.ts
> +    do {
Роберт Мартин "Чистый код"

2023-01-03 21:46 UTC, merged