sprint 4
Winterstein9/middle.messenger.praktikum.yandex pull request #7
Opened 2023-01-20 03:39 UTC by Winterstein9

2023-01-20 06:54 UTC, maks88sgt requested changes
Привет. Я проверял твою работу на 3 спринте, поэтому не фокусировался на функционале и коде компонентов - в целом все было в порядке. Из прошлых замечаний обратил внимание на отсутствие EOF, что следовало бы поправить. 
Что касается 4 спринта, то работу пока принять не могу по нескольким причинам:
1. Отсутствуют тесты.
2. Не настроен прекоммит хук.
3. Докер файл нужно поправить, чтобы не полагаться на наличие ручной продакшн сборки и более эффективно использовать ресурсы.
4. Readme файл не обновлен в соответствии с последними обновлениями проекта.

2023-01-20 06:54 UTC, maks88sgt commented on .hintrc
> +}
Здесь гит ругается на отсутствие EOF. Уже писал об этом в прошлом ревью, стоит настроить ИДЕ чтобы это делалось автоматически

2023-01-20 06:54 UTC, maks88sgt commented on Dockerfile
> +CMD ["node", "express.js"]
Для контейнера можно сразу взять образ с установленной версией ноды. Также, образ полагается на папку dist, которая добавлена в гитигнор и соответственно ее нет в репозитории. Т.е. для создания образа нужно чтобы продакшн билд был собран руками, что может привести к проблемам.

2023-01-20 06:54 UTC, maks88sgt commented on package.json
> +    "chai": "^4.3.7",
Здесь стоит использовать фиксированные версии зависимостей как в остальных случаях.

2023-01-20 06:54 UTC, maks88sgt commented on package.json
> +    "eslint-config-airbnb": "19.0.4"
В списке зависимостей нет express, хотя он нужен для работы сервера

2023-01-23 01:30 UTC, Winterstein9 commented on Dockerfile
> +CMD ["node", "express.js"]
> Для контейнера можно сразу взять образ с установленной версией ноды. Также, образ полагается на папку dist, которая добавлена в гитигнор и соответственно ее нет в репозитории. Т.е. для создания образа нужно чтобы продакшн билд был собран руками, что может привести к проблемам.

Привет. Образ с установленной нодой весит 234 мб, если инсталлировать то 69мб. С целью экономии мб и был выбран данный метод создания образа.

2023-01-23 03:11 UTC, maks88sgt commented
Привет. Нужно внести еще кое-какие изменения, чтобы идти дальше:
1. Добавить тесты для модуля отправки запросов (требуются по условиям скрипта)
2. Донастроить прекоммит хук. У тебя фактически установлена 8 версия, а конфиг написан для 4 (хук указан в packge.json) и такая конфигурация не работает.

2023-08-29 17:35 UTC, merged